workspace:
  name: LaTeXPaper_2_Beamer
  description: >
    This is the main workspace containing several (2) projects. 
    In this case the purpose is to convert a LaTeX research paper (or book chapter) to a LaTeX beamer presentation.
  action_prompts_folder: ./action_prompts
  projects:
    - name: Book Chapter
      project_handle: chap
      description: This is the book chapter in the original form created. 
      project_folder: book_chapter_project
      # These are subfolders within project_folder (you rarely change these settings)
      components_folder: components
      supporting_files_folder: supporting_files
      results_folder: results
      build_folder: build
    - name: Presentation
      project_handle: pres
      description: This is a presentation with the material as appearing in the book chapter.
      project_folder: presentation_project
      # These are subfolders within project_folder (you rarely change these settings)
      components_folder: components
      supporting_files_folder: supporting_files
      results_folder: results
      build_folder: build
  # This section is about aids to prompts used for the whole workspace
  workspace_system_prompts:
    latex_requirements_file: latex_packages.txt
